# Generated by Django 5.0.4 on 2024-09-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_tags_delete_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
